# Generated by Django 5.2.12 on 2026-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_job_experience_alter_job_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
